#!/bin/sh
#
# Dependencies: jq, curl

echo "Content-type: text/html"
echo
echo "<!DOCTYPE html>"

echo "
<head>
    <link rel='stylesheet' type='text/css' href='/discover.css'>
    <title>Discover</title>
</head>"

site=$(echo "$QUERY_STRING" | sed -n 's/^.*url=\([^&]*\).*$/\1/p' | sed "s/%20/ /g" | sed "s/+/ /g")
[ $site -z ] && site=$HTTP_HOST
json=$(curl -s "https://"$site"/.well-known/discover")

preview()
{
    if response=$(curl -sf "$1/.well-known/discover");
    then
        echo "$response" | jq -r '"<strong>" + .name + "</strong><a href=\"?url=" + .location[8:] + "\"><img src=\"" + .image + "\"></a>"' 2> /dev/null
    fi
}

read -d "\n" -p -r name homepage image_url <<< "$(echo "$json" | jq -r '.name, .location, .image')"

echo "<body>"
echo "<nav>"
echo "<h1>$name</h1>"
echo "(<a href=\"$homepage\">$homepage</a>)"

## Contact
echo "$json" | jq -r '.contact | to_entries | map("<p>" + "<strong>" + .key + "</strong>" + "<em>" + .value + "</em>" + "</p>") | join("\n")'
echo "<img src=\"$image_url\">"

## Resources
echo "<h2>Website Content</h2>"
echo "<ul>"
echo "$json" | jq -r '.resources | map("<li>" + "<a href=\"" + .location + " title=\"" + .description + "\">" + .label + "</a></li>") | join("\n")'
echo "</ul>"
echo "</nav>"

## Connection Groups
echo "<main>"

echo "$json" | jq -r '.connection_groups | to_entries | map([.key] + .value) | map(join(",")) | join("\n")' | while read -r line; do
    name=$(echo "$line" | cut -f1 -d ',')
    echo "<h3>$name</h3>"
    echo "<ul>"
    for url in $(echo "$line" | cut -f2- -d ',' | tr ',' ' '); do
        echo "<li>"
        preview "$url"
        echo "<a href=\"$url\">$url</a></li>"
    done
    echo "</ul>"
done

## Connections
echo "<h3>Links</h3>"
echo "<ul>"

echo "$json" | jq -r '.connections | join("\n")' | while read -r url; do
    echo "<li>"
    preview "$url"
    echo "<a href=\"$url\">$url</a></li>"
done
echo "</ul>"

echo "</main>"
echo "</body>"

