#!/bin/sh
#
# CGI script for discover protocol

echo "Content-type: text/html"
echo

site=$(echo "$QUERY_STRING" | sed -n 's/^.*url=\([^&]*\).*$/\1/p' | sed "s/%20/ /g" | sed "s/+/ /g")
[ $site -z ] && site=$HTTP_HOST
json=$(curl "https://$site/.well-known/discover")

parse()
{
    echo $(echo $json | python -c "import json,sys;obj=json.load(sys.stdin);print(obj['$1']);")
    return
}

parse name
echo
echo "<img src='$(parse image)'>"

exit 0
